# Generated by Django 3.2.4 on 2021-07-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellidoM',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_adq',
            new_name='fecha_de_adquisicion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellidoP',
        ),
    ]
