# Generated by Django 3.2.4 on 2021-07-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_auto_20210703_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido_materno',
            new_name='apellidos',
        ),
    ]
