# Generated by Django 3.2.4 on 2021-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_rename_apellido_materno_empleado_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
