# Generated by Django 3.2.4 on 2021-07-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alter_producto_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
