# Generated by Django 3.2.4 on 2021-07-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_auto_20210704_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo_de_adquisicion',
            field=models.PositiveIntegerField(),
        ),
    ]
